apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  ports:
  - name: nginx
    port: 9001
    targetPort: 80
  - name: multitool
    port: 9002
    targetPort: 8080
  selector:
    app: main