---
- name: Install Clickhouse
  hosts: clickhouse
  remote_user: root
  roles:
    - clickhouse
  tasks:
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0

- name: Install vector
  hosts: vector
  remote_user: root
  roles:
    - vector

- name: Install Lighthouse
  hosts: lighthouse
  roles:
    - lighthouse