---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: multitool
          image: praqma/network-multitool:alpine-extra
          imagePullPolicy: IfNotPresent
          env:
            - name: HTTP_PORT
              value: "8080"
        - name: nginx
          image: nginx:1.19