---
- name: test my_own_module
  hosts: localhost
  tasks:
  - name: run module
    my_own_module:
      path: '/tmp/testfile.txt'
      content: 'NEW Example text message'
    register: testout
  - name: dump test output
    debug:
      msg: '{{ testout }}'

